[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x720x16
autorestart=true
priority=1

[program:xfce4]
command=/usr/bin/startxfce4
environment=DISPLAY=":1",HOME="/root"
autorestart=true
priority=2

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -nopw -listen 0.0.0.0 -xkb -forever -shared
autorestart=true
priority=3

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
autorestart=true
priority=4
